stages:
  - lint
  - test
  - build
  - deploy
  
variables:
  DOCKER_DRIVER: overlay2

default:
  image: python:3.10-slim
  
install_dependencies:
  script:
    - pip install -r requirements.txt

lint:
  stage: lint
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - app/**/*
        - tests/**/*
  script:
    - flake8 app/
    - echo "No lint issues found."

test:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - app/**/*
        - tests/**/*
  script:
    - pytest

build:
  image: docker:latest
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - app/**/*
        - tests/**/*
  variables:
    IMAGE_TAG: $CI_REGISTRY/flpfranca/pilar-case:$CI_COMMIT_BRANCH
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  image: alpine:3.16.0
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - app/**/*
        - tests/**/*
  script:
    - apk add --no-cache openssh-client curl
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - ssh-keyscan -H ec2-18-230-21-62.sa-east-1.compute.amazonaws.com >> ~/.ssh/known_hosts
    - ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-230-21-62.sa-east-1.compute.amazonaws.com 'bash /home/ubuntu/deploy.sh'