stages:
  - lint
  - test
  - build
  - deploy
  
variables:
  DOCKER_DRIVER: overlay2
  
lint:
  image: python:3.10-slim
  stage: lint
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - app/**/*
        - tests/**/*
        - Dockerfile
        - entrypoint.sh
  script:
    - pip install -r requirements.txt
    - flake8 app/
    - echo "No lint issues found."

test:
  image: python:3.10-slim
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - app/**/*
        - tests/**/*
        - Dockerfile
        - entrypoint.sh
  script:
    - pip install -r requirements.txt
    - pytest


build:
  image: docker:latest
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - app/**/*
        - tests/**/*
        - Dockerfile
        - entrypoint.sh
  variables:
    IMAGE_TAG: $CI_REGISTRY/flpfranca/pilar-case:$CI_COMMIT_BRANCH
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG


deploy:
  image: alpine:3.16.0
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - app/**/*
        - tests/**/*
        - Dockerfile
        - entrypoint.sh
  script:
    - apk add --no-cache openssh-client curl
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - scp -o StrictHostKeyChecking=no deploy.sh ubuntu@ec2-18-230-21-62.sa-east-1.compute.amazonaws.com:/home/ubuntu/
    - scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@ec2-18-230-21-62.sa-east-1.compute.amazonaws.com:/home/ubuntu/
    - ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-230-21-62.sa-east-1.compute.amazonaws.com 'bash /home/ubuntu/deploy.sh'